# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5018c5125917e09f1497351dd4c1a1398daa450e34c69107398a430fedec66cf5a053087103e452d6f7d340c12158b18daec941436a85a6d632a1798f735f68d

test:
  secret_key_base: e033a7aeeb2aafa11de627765f35ef6120d6bed3d1e5081d0c64eb41858da95448b3c959a7c3d7314c95f4753adfcb954ac88439bb6da01f40588e17c79e63df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
